---
- name: Installing Multiple packages
  hosts: all
  become: true

  vars: 
    package_name: 
      Ubuntu: apache2
      Amazon: httpd

  tasks: 
    - name: Install packages on Ubuntu
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - apache2
        - git
        - nodejs
      when: ansible_distribution == "Ubuntu"

    - name: Install packages on Amazon AL2
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - apache2
        - git
        - nodejs
      when: ansible_distribution == "Amazon"

    
      