---
- name: Installing Apache, Nginx and cronjob configuring it
  hosts: all
  become: true
  vars: 
    apache_package_name: 
      Ubuntu: apache2
      Amazon: httpd
  tasks: 
    - name: Printing OS versions
      debug:
        msg: "This OS is {{ ansible_distribution }}"
        
    - name: Install apache webserver on Al2
      yum: 
        name: "{{ apache_package_name['Amazon'] }}"
        state: absent
      when: ansible_distribution == "Amazon"

    - name: Install apache webserver Ubuntu
      apt: 
        name: "{{ apache_package_name['Ubuntu'] }}"
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Install Nginx on Al2
      yum:
        name: nginx
        state: present
      when: ansible_distribution == "Amazon"
    
    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Cronjob
      yum:
        name: cronie
        state: present
      when: ansible_distribution == "Amazon"
      
    - name: Install Cronjob
      yum:
        name: cron
        state: present
      when: ansible_distribution == "Ubuntu"
      
    - name: Start Nginx 
      service:
        name: nginx
        state: started
        enabled: true
      when: ansible_distribution == "Amazon"
      