---
- name: Installing Nginx and cronjob configuring it
  hosts: webservers
  become: true

  tasks: 
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Install Cronjob
      yum:
        name: cronie
        state: present
    
    - name: Start Nginx 
      service:
        name: nginx
        state: started
        enabled: true