---
- name: Installing Apache, Nginx and cronjob configuring it
  hosts: all
  become: true
  vars: 
    apache_package_name: 
      Ubuntu: apache2
      Amazon: httpd
    cron_package_name:
      Ubuntu: cron
      Amazon: cronie
    package_names: 
      - pk_name: "{{apache_package_name[ansible_distribution]}}"
      - pk_name: "{{cron_package_name[ansible_distribution]}}"
      - pk_name: nginx
      - pk_name: git
      - pk_name: nodejs
      - pk_name: docker
  tasks: 
    - name: Install packages
      package: 
        name: "{{ item.pk_name }}"
        state: present
      with_items: "{{ package_names }}"

    - name: Start Nginx 
      service:
        name: nginx
        state: started
        enabled: true
      