
#SPDX-License-Identifier: MIT-0
---
# main file for ec2_launch
- name: Adding SSH access to a security group
  amazon.aws.ec2_group:
    name: zaki-security 
    description: Security group for Ec2 instances launched via ansible
    region: ap-south-1
    rules:
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress: 
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: security_group

- name: Launch Ec2 instnace
  amazon.aws.ec2_instance:
    name: Ansible-created-instance
    key_name: zaki-test
    region: ap-south-1
    instance_type: t2.micro
    image_id: ami-0fd05997b4dff7aac
    count: 1
    security_group: "{{ security_group.group_id }}"
  register: ec2

- name: Waiting for instance to be ready
  wait_for: 
    host: "{{ ec2.instances[0].public_dns_name }}"
    port: 22
    delay: 30 
    timeout: 300
    state: started
  when: ec2.instances is defined and ec2.instances | length > 0

- name: Add the Ec2 instance to the inventory dynamically
  add_host: 
    name: "{{ec2.instances[0].public_dns_name}}"
    groups: dynamic_hosts
    ansible_ssh_private_key_file: "/Users/zakimd/Desktop/devops/zaki-key.pem"
    ansible_user: ec2-user
  
- name: Debug dynamic inventory
  debug: 
    var: groups['dynamic_hosts']